var cfg = require('./config');

exports.render = function(doc, data) {
  doc.moveUp(12.7);
  doc.
    fillColor(cfg.color.orange).
    font(cfg.font.boldface).
    fontSize(cfg.font.h3).
    moveUp(1.2).
    text('Resume', cfg.column.two.start + 170);
  doc.moveDown(0.5);
  doc.
    fillColor(cfg.color.gray).
    font(cfg.font.face).
    fontSize(cfg.font.small).
    text(
      'This PDF resume was automatically generated by a Node.js script ' +
      'which pulled in my live resume info from the LinkedIn API.',
      { width: 100 }
    );
  return(doc);
};
